apiVersion: v1
kind: Pod
metadata:
  name: pod02
spec:
  containers:
    - name: nginx
      image: nginx

    - name: mongo
      image: mongo
---
apiVersion: v1
kind: Pod
metadata:
  name: pod03
  annotations:
    training/course: devops
  labels:
    type: test
spec:
  containers:
    - name: nginx
      image: nginx

    - name: mongo
      image: mongo

