apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      type: rs
  template:
    metadata:
      labels:
        tier: frontend
        type: rs
    spec:
      containers:
        - name: php-redis
          image: nginx
